# Generated by Django 3.1.5 on 2021-08-15 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_auto_20210815_0257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='first_paragraph',
            new_name='firstParagraph',
        ),
    ]
